spring:
  application:
    name: firstSpringBoot
  datasource:
      url: jdbc:mysql://localhost:3306/mystore2?createDatabaseIfNotExist=true
      username: root
      password: password
  jpa:
    show-sql: true

